site_name: Zihan Tutorials
site_url: https://ZihanNing.github.io/zihan-tutorials/
repo_url: https://github.com/ZihanNing/zihan-tutorials

theme:
  name: material

nav:
  - Home: index.md
  - Bloch Simulation:
      - 1 - Basic Bloch Equation: bloch_simulation/1-basic_bloch_equ/index.md
      - 2 - Bloch Simulation (Components): bloch_simulation/2-bloch_sim_comp/index.md
  - Tutorials 2:
      - Tutorials 2: tutorials2/Tutorials2.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      accent: indigo
    - scheme: slate
      primary: grey
      accent: indigo

